### PR TITLE
added chat to project

### PR DESCRIPTION
**Pull request by ericarmstr0ng**

### CODE REVIEW

**Comment by cdavis4** [comment]
- I think it might help to separate out the views into different files. One for each view or struct

**Comment by cdavis4** [comment]
put them into a folder called chat
Please put all the folders, files you are using for Chat in a folder called Chat. I think it will help to keep the organization cleaner when searching for files.

**Comment by cdavis4** [comment]
I'm closing this for now until the bug is resolved and changes made to help find bug

**Comment by nschaffner** [comment]
I am closing this pull request as we have merged an updated chat branch to the Master branch, which supersedes this pull request.

**Pull request closed without merging**
